name: Flutter Linux Build

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true
    - run: flutter pub get
    - name: Flutter Linux Build
      run: |
        sudo apt-get update -y
        sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libblkid-dev libgtk-3-0 libblkid1 liblzma5 libsecret
        flutter config --enable-linux-desktop
        flutter build linux        
    # 成果物アップロード
    - name: artifact upload
      uses: actions/upload-artifact@v2.2.0
      with:
        # 保存ファイル名（name.zip）
        name: linux
        # 保存するファイル
        path: ./build/linux/
        # 保存期間（日）
        retention-days: 1
  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true
        architecture: x64
    - run: flutter pub get      
    # macos Build
    - run: flutter config --enable-macos-desktop
    - run: flutter build macos
    # 成果物アップロード
    - name: artifact upload
      uses: actions/upload-artifact@v2.2.0
      with:
        # 保存ファイル名（name.zip）
        name: macos
        # 保存するファイル
        path: ./build/macos/
        # 保存期間（日）
        retention-days: 1
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - run: flutter pub get
      - name: Flutter Build Windows
        run: |
          flutter config --enable-windows-desktop
          flutter build windows          
      # 成果物アップロード
      - name: artifact upload
        uses: actions/upload-artifact@v2.2.0
        with:
          # 保存ファイル名（name.zip）
          name: windows
          # 保存するファイル
          path: ./build/windows/runner/Release/
          # 保存期間（日）
          retention-days: 1
